### ISSUE TITLE
[BUG] After leaving a server and starting a new one, screen elements are preserved from old servers

### ISSUE THREAD

**Issue by SlowDeepExhalation** [AoTTG-2/AoTTG-2#132]
**Bug:** When you leave a server, screen elements (such as titan number, time, KD, the pause menu, and targeting reticle) are invisible while in the main menu, but will reappear when you begin a new server.  The new server's elements will just be stacked on top of it, overlapping and making both nearly unreadable.  You can stack multiple servers' worth of screen elements, there does not seem to be an upper limit. 

**To Reproduce:**
1.Start a server.  Trost - Colossal titan is a good choice.
2.Pause and quit out of the server.
3.Start a new server, like city or forest.  You'll see the instructions to kill the colossal titan remain on screen.

**Expected behavior:**
Screen elements should be cleaned on exit from the server.  The server should look the same even if you quit out of a another server earlier.

**Additional information:**
Screenshot: https://i.imgur.com/BHanxXn.png
Output log: (attached)
[output_log - Overlapping text bug.txt](https://github.com/AoTTG-2/AoTTG-2/files/4614847/output_log.-.Overlapping.text.bug.txt)

**Comment by Lithrun** [comment]
@AoTTG-2/development-team 
When main menu is opened, we create a canvas. When players leave an in-game round, they return to the main menu, and since the main menu is opened again, we again create a new canvas. So, before creating a canvas, simply check if the Canvas object already exists.
The same applies to "CommandLine", "InputManagerController"

![image](https://user-images.githubusercontent.com/22615133/81674828-ecb2ae80-94a1-11ea-8418-1144df6a07a3.png)

- Use the Editor and check the DontDestroyOnLoad
- Create a lobby and press quit (Press Esc in-game)
- The CommandLine, InputManagerController and Canvas are created again

- [x] Don't create a new Canvas, CommandLine and InputManagerController if they already exist
