### ISSUE TITLE
[BUG] Moving crusher blocks at the end of Akina are synchronized

### ISSUE THREAD

**Issue by SlowDeepExhalation** [AoTTG-2/AoTTG-2#146]
**Describe the bug**
The seven moving crusher blocks near the end of Akina all move in perfect sync, forming a perfect row.

**To Reproduce**
1. Play Akina racing.  Get to the blocks.  Look at them.

**Expected behavior**
The blocks should not be synchronized.  Each should move independently of the others.

**Additional Information
Build: Stresstest
~~Screenshots of current Stresstest's blocks and RCMod's blocks included.~~
Error with Github's upload.  Imgur links instead:
Synchronized blocks (the bug): https://i.imgur.com/xzmAUEe.png
Normal blocks in RCMod: https://i.imgur.com/UHIymo3.png

**Comment by Lithrun** [comment]
Objects are moved via a class known as "LevelMovingBrick". It goes from location A, to location B. Script already has a bool field named "Towards A". Unchecking this values makes it go into opposite direction, so that not every object moves into the same direction.

- [ ] Investigate in AoTTG on the Akina racing map which moving objects need to go what way, and then simply match this with the "Towards A" field.

**Comment by JupiterJaeden** [comment]
I've fixed this issue and created a pull request. Once it is reviewed and (hopefully) accepted, this issue can be closed.

**Comment by SlowDeepExhalation** [comment]
Please do not close bug issues without having testers confirm that they are fixed.

The first pair of moving crusher blocks seems to be working properly in Issue98.  The second set (of three blocks) is not working properly; the third block moves in perfect synch with the first when it should not be synchronized (see attached pictures).  I observed the map from above in Anarchy (which is impossible in AoTTG 2, because the game automatically restarts 20s after completing the race), and I think the difference is that the third block moves at a higher speed than all the others.

Finally, the last pair of blocks (the pair with a block that's still solid, but made entirely of lava) isn't correct either.  Pictures don't really show it, but one should lag behind the other more than it does currently.  They move at the same speed, but it seems like one of them was delayed by about a half second behind the other.
![semisynchronized crusher blocks, set #2, AoTTG2](https://user-images.githubusercontent.com/64349026/83346047-46f7a000-a2e7-11ea-991a-ce9a54ba092a.png)
![Desynchronized crusher blocks, set #2, Anarchy](https://user-images.githubusercontent.com/64349026/83346059-60005100-a2e7-11ea-8e05-7466ef77a97d.png)

**Comment by SlowDeepExhalation** [comment]
http://cdn.discordapp.com/attachments/709714243749937152/768216328762294302/AkinaCrusherComparison.mkv

The above linked video shows the current state of the Akina crushers as of TBG's contributions (AKINA-CRUSHER build, as seen in the lower left).  On the left side is how the crushers move in AoTTG 2; on the right is RCMod.  I synchronized the time as best I could, so if AoTTG 2's version of Akina were working perfectly, both sides should be basically identical.

Clear problems:
--The second block is synchronized with the first block (again?), when it should be moving in the opposite direction.
--The third and fourth blocks (in the front of the second group) appear to be moving in the opposite direction they should be moving in.  Either that, or their starting positions are incorrect; I can't test this without having some way of viewing the blocks, frozen, at the very start of the map.
--The fifth block (in the rear of the second group) is moving at the same speed as the fourth block (it takes 4.5 seconds to move between the walls).  It should be faster by 50%; in RC mod it only takes three seconds to move between the walls.
--The sixth and seventh blocks seem to be correct as far as speed and direction, but seem to lag behind where they should be by about a second.

I don't consider this to be a particularly high priority, and it may take more work to fine tune the crushers to be *identical*, even if all four of these issues are fixed.

**Comment by Acros5542** [comment]
Update: As of Alpha 0.2, crushers 1 and 2 are no longer synced, instead moving in opposite directions. Crusher 5 is still too slow, as it's synced exactly with crusher 3. All other issues _seem_ to still be occurring, but I'm not positive, it probably would take a custom build to truly make sure, as testing it in game is quite difficult.

**Comment by desu7** [comment]
As of Alpha 3:
Blocks 1, 3, 5 and 7 are synced; Blocks 2, 4, 6 are synced but in the opposite direction.

In AoTTG, Blocks 1,3,7 are in sync, while Blocks 2 and 4 are also synced but in the opposite direction. Looking at blocks 5 and 6 in game, it looks like Block 5 starts synced with the odd blocks, but it looks like it is slighty faster since it can take lead on other blocks (this is also visible in the footage SlowDeepExhalation posted), while Block 6 is synced with the even blocks, but it looks like it's slower than the rest since it falls behind the other blocks.

This should be checked better in Unity, because I could be wrong but it's def not fixed yet.
