### ISSUE TITLE
Unity Assets Structure Maintainability

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#193]
**How will this enhancement improve the game?**
Currently, the way assets are structured within the project are still identical to AoTTG. However, this is still quite a mess. The assets are not properly structured, which makes it difficult to find what you are looking for. Improving this structure will allow the other teams to also more easily navigate within the project. Like the mapping team can easily locate 3D assets, art team knows where to place new assets and the developers can find the prefabs where it makes sense.

**Describe the solution you'd like**
Assets that are structure, so that they can easily be found.

**Comment by Lithrun** [comment]
Will work on this one, so that less experienced contributors can easily navigate throughout the files

**Comment by mwnDK1402** [comment]
Consider using tags. I heard someone mention that they sort their project files by feature, not type, because they can search by type in the editor with the `t:` flag. So we would have a MindlessTitan directory, which has all models, prefabs, sounds, and scripts related to the titan. If this makes it harder to find something, we can utilise tags.

**Comment by Lithrun** [comment]
Sorting by feature does indeed make more sense. Main concern for this issue however, is the fact that any in progress issues may encounter serious merge conflicts, as the files they are modifying are moved. Should discuss in dev squad when to time this correctly, but on an asap notice, since mappers should wait until this is done

**Comment by Lithrun** [comment]
Closing this issue as #717 will cover this
