### ISSUE TITLE
[BUG] Elastic collisions

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#273]
**Describe the bug**
Some colliders appear to be elastic. It seems like that something has changed with the Physic material. Please play around with its settings and determine an more appropriate configuration: https://docs.unity3d.com/Manual/class-PhysicMaterial.html

For the player, you are can the PhysicsMaterial under `Assets/PhysicsMaterial/player_body`

**To Reproduce**
1. Play any map, and try to bounce into different objects. Compared to AoTTG, this will feel different and you are bounced more often.

**Expected behavior**
The behavior is expected to be identical to AoTTG. This issue will take a while, as it requires fine tuning the settings.

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Mi-Sad** [comment]
Seems like the HERO prefab didn't had the player physics material on it and also it's angular drag was off, being 0 instead of 0.05 beside those there where no difference in setting with AoTTG, the physics system whatsoever does behave slightly differently from AoTTG but to a degree which i would assume acceptable, alternatively i can try to turn the dinamic drag a little bit higher to try mimic the old behave better.
![Cattura di schermata (1099)](https://user-images.githubusercontent.com/65404701/93399963-f64c8880-f87e-11ea-89cc-15a759e2c6ea.png)
![Senzanome](https://user-images.githubusercontent.com/65404701/93400056-314ebc00-f87f-11ea-8ad3-54c687807f3d.png)
