### ISSUE TITLE
[BUG] Death/Scoreboard Inconsistencies

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#349]
**Describe the bug**
Depending on which way you die, there will either be a message in the kill feed or not, additionally, any "death method" that doesn't appear in the feed, does not update your death counter on the scoreboard.

Normal titans' double-swing attack and Jumpers' leaping bite attack seem to be the only attacks to cause the message to appear in the kill feed (shown as you killing yourself).
Deaths from Annie also show up in the kill feed and update the death counter, but these are different as it says "Female Titan" has killed you instead.

**To Reproduce**
1. Go into a lobby
2. Experience the cold embrace of death
3. Look at kill feed and scoreboard

**Expected behavior**
Regardless of how you die, the death counter on the scoreboard should increase by 1, and all titans should have appropriate kill messages in the kill feed.

**Video**
https://youtu.be/snXpmnlPPDw

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
Please also resolve #167 for this one. Killfeed messages are managed by the obsolete: `private void updateKillInfo(bool t1, string killer, bool t2, string victim, int dmg)` RPC. To resolve this particular bug, each usage of this RPC has to be investigated. If possible, also refactor this RPC & related methods.

The one related to Hero (GUEST kills GUEST, whereas it should be GUEST kills TITAN), is caused inside TriggerWeaponCollider.HeroHit. If changes to HERO need to be made, and #33 is not complete yet, consult @Lithrun for HERO changes. It uses the name of owner of the titan, rather than the name of the titan. Missing killfeed from titan attacks is most likely caused because they simply do not call the RPC.
