### ISSUE TITLE
Basic Map Prefabs 

### ISSUE THREAD

**Issue by HawkeMaylan** [AoTTG-2/AoTTG-2#365]
@AoTTG-2/mapping-team 
**How will this feature improve the game?**
Having prefabs for the mapping team will improve map making proficiency

**Describe the solution you'd like**
Creating prefabs in a structured way would allow map makers to easily create the maps.

**Comment by FAStre** [comment]
I'm not sure how mapping/and or map prefabs work at all, but is it possible to have a standard map ground/terrain/floor GameObject with a certain name, or a naming convention for it? I ask because currently #113 auto scales to maps by taking the size and center of the floor/ground/terrain of the map and then scaling and fitting appropriately to it. So if a map automatically has the name set as "GroundTerrain" no additional changes would need to be made to the map in terms of renaming the ground to be compatible with #113 , as the code in #113 searches for "GroundTerrain" when making it's calculations on how to fit and rotate around a map.

**Comment by HawkeMaylan** [comment]
Making a Prefab for maps terrains would very well be possible but there's not much reason for making a prefab for a terrain for all of the mappers to work on as it is quite easy to just change the name to "GroundTerrain."  This issue is more so I can upload the different map prefabs to the development branch for all of the mappers to easily merge and use. I can set up a terrain prefab for the maps and add it in under a terrain directory with the specific settings as this wouldn't take much time to do but as most of the terrains are already complete most terrains will just need to be renamed. Thank you!

**Comment by FAStre** [comment]
Ok cool thanks for the reply, and good luck with the issue.

**Comment by FAStre** [comment]
@HawkeMaylan #113 is nearly finished and a daynightcycle prefab is now nearly ready for use. A default time can easily be set(so map makers can easily configure the time of day of a scene) and other options configured too.

I recommend that we include this prefab for map makers, it's as simple as dragging this prefab onto a scene I think.

**Comment by HawkeMaylan** [comment]
Sounds good, before I can continue working on this I need to try and get my entire team onto GitHub as many are very reluctant. I'll see how soon I can get working on both this and the hierarchy, hopefully it should be within the week.

**Comment by FAStre** [comment]
@HawkeMaylan Be sure to have mappers add the DayAndNightController prefab in their maps, it can be found at Assets/Resources/Day And Night Controller

**Comment by dark3art** [comment]
prefabs have been made for mappers so this issue is outdated and i'm closing it so the github page get's cleaned up
