### ISSUE TITLE
[BUG] Typing triggering flares

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#368]
**Describe the bug**
Typing numbers in either the menu or chat will shoot off the corresponding flare as soon as the chat/menu is closed.

**To Reproduce**
1. Create a single or multiplayer lobby
2. Open the chat
3. Type "1" and press enter

**Expected behavior**
Typing in the chat or menu shouldn't trigger any inputs for abilities or items.

**Log file**
https://www.dropbox.com/s/rfjv6indq043ju9/Flare.txt?dl=0

**Additional context**
This seems to only happen with flares, for example typing "q" will not trigger you to shoot a hook once the menu/chat is closed.

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
Within InputManager.KeyDown(InputHuman input), Line 317, there's an if statement which allows Item1 to be executed when a menu is open. This was added because of the functionality for spectator mode.. Find a work around which allows Item1 to be used when it is for spectator mode, but that it cannot be used when it is used for flares.

If no work around can be found, we may want to consider to add a new keybind for the spectator mode
