### ISSUE TITLE
[BUG] Abnormally high jumping in Utgard when on the castle

### ISSUE THREAD

**Issue by atirutw** [AoTTG-2/AoTTG-2#530]
**Describe the bug**
The jump height in Utgard when jumping on the castle tower and some other parts are at least 6 times the normal jump height.

**To Reproduce**
1. Start a game in the Utgard map
2. Jump on the castle(the spawn tower is 100% effected)

**Expected behavior**
Jump height should be the same as in other maps

**Screenshots**
![image](https://user-images.githubusercontent.com/25323231/106775843-12a66180-6676-11eb-88cb-1e892ca86e6c.png)

https://user-images.githubusercontent.com/25323231/106775881-1df98d00-6676-11eb-99af-2756dac3b2b7.mp4

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by atirutw** [comment]
I decided to do some more investigation about this and it seem something is really wrong with the castle's collider. Some part of the castle model makes you jump really high.

**Comment by Acros5542** [comment]
Wonder if this helps explain #488 
Also this has been a known issue since the map was implemented, no harm in giving it a report though

**Comment by atirutw** [comment]
> this has been a known issue since the map was implemented

I guess this is what happens when you make a big mesh in one piece instead of multiple pieces.

Oh right. Speaking of meshes, I noticed z-fighting on some parts of the castle. Could this be related?

**Comment by DjFrytek** [comment]
When I worked on racing ring colliders issue, there was a problem when player would jump really high when standing on the ring, the steeper the slope, the higher the jump. I ended up dissecting the ring into smallest parts possible, but it would still happen. I believe the problem was with it using mesh collider, or something along those lines while also not having all sides, meaning you could walk inside of the shape without having to cross any walls, and it made mesh collider create weird concave shapes instead, which I believe was also the reason of high jumps. I ended up just disabling collision for rings, and making a child object for every part of the ring and creating an invisible box with a collider on it. I would suggest trying to just manually create invisible collider that would fit the castle model and if that proves troublesome, or just plainly a bad solution, which might be the case with such big model, try to make the model closed, so it doesn't have any hollow sides and it might just work.
