### ISSUE TITLE
Weaken/nerf Titan Shifters

### ISSUE THREAD

**Issue by KoroSensei0320** [AoTTG-2/AoTTG-2#56]
**How will this enhancement improve the game?**
The majority of AoTTG players greatly dislike Titan Eren and don't want them in the lobbies.
Weakening Eren's ability would make it less hated, which could hope to return Eren to the game after being essentially redundant. The overwhelming majority (over 80%) of people agreed that Eren's ability should be weakened.
**Describe the solution you'd like**
For Titan Shifters to be heavily nerfed.
The link below has many useful
 suggestions!
https://cdn.discordapp.com/attachments/683107211983323164/699915285100101632/Weaken-Nerf_Titan_Shifters.pdf
- SaintNAIWA's suggestions.

**Comment by KoroSensei0320** [comment]
Pasting the link below will bring up a PDF full of suggestions!
https://cdn.discordapp.com/attachments/683107211983323164/699915285100101632/Weaken-Nerf_Titan_Shifters.pdf
- SaintNAIWA's suggestions.

**Comment by Lithrun** [comment]
Main ideas from the community:
- Implement a stamina functionality for titan shifters. Using an attack will drain X stamina, and it will slowly refill similar to have player titans work. This can prevent constant spamming of attacks without consequences
- Make titan shifters do damage to titans if health mode is enabled.
- Give titan shifters health, so that they will take damage if titans attack them. Currently they are invulnerable and can only be killed if a titan collides through the player titan where the player model is positioned. Additionally, hostile players can also damage the titan shifter.

**Comment by CoronaryLilim** [comment]
At the behest of Disciple/Mr. Lurkin, i'm going to paste my suggestions for a shifter rework.
https://pastebin.com/zQ5p1yiW

**Comment by Prolonpo** [comment]
The new sets of proposals for shifters might also address the current situation of Titan Shifters being over-powered.

Wondering if I should close this issue as this issue might become redundant after the talk from the Titan Shifter proposal that are also aimed at making them more balanced.

**Comment by Prolonpo** [comment]
After consulting with the staff, this issue was deemed redundant with how AoTTG2 has currently progressed.

Reference: https://discord.com/channels/681641241125060652/683483289289621515/870323723884961864

Closing this issue.
