### ISSUE TITLE
Characters: Armin, Connie, Eren, Hanji, Jean, Marco, Mike, Petra, Rico, Sasha

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#653]
**How will this enhancement improve the game?**
Currently we have Annie, Kenny, Levi, Mikasa & Pixis. So let's add the remaining ones.

**Describe the solution you'd like**
Create the Character Presets for Armin, Connie, Eren, Hanji, Jean, Marco, Mike, Petra, Rico, Sasha

**Comment by sxlksxskul** [comment]
Currently all newly added characters so far (Armin, Eren, Jean, Marco, Petra) have no hair as there are no options for the specific characters, all newly added male characters have "Uniform MB 1" as their outfit, Petra's outfit is currently "Uniform FB Annie" as there are no other options for female outfits besides "Uniform FB Mikasa". I also noticed that there is no option for Sasha's ability when choosing a skill in a character build, is her skill not coded yet? Are the outfits for the male characters fine for now? Will more female outfits be added?  Will hair for each character be added? @Lithrun so many questions

**Comment by sxlksxskul** [comment]
So two problems have popped up (credit to Crimson Hunter for letting me know).

![image](https://user-images.githubusercontent.com/84128082/125311624-73c01880-e32b-11eb-970a-d179e3954193.png)
The first problem would be weird white textures as seen above. This problem seems to have been present for a good while since the first characters (e.g. Mikasa) all have this problem. Most likely hasn't been noticed due to the characters hair and might not be a big issue, but in Connie's case this problem is really noticeable.  A new issue should be made for this problem.

![image](https://user-images.githubusercontent.com/84128082/125312149-f052f700-e32b-11eb-9230-3d269cc8fd73.png)
The second problem would be, as seen above, the newly added characters all have white hair. This is an error on my end that I can't seem to find a solution for and I think before closing this issue, this problem needs to be solved.

**Comment by Lithrun** [comment]
> ![image](https://user-images.githubusercontent.com/84128082/125311624-73c01880-e32b-11eb-970a-d179e3954193.png)
> The first problem would be weird white textures as seen above. This problem seems to have been present for a good while since the first characters (e.g. Mikasa) all have this problem. Most likely hasn't been noticed due to the characters hair and might not be a big issue, but in Connie's case this problem is really noticeable. A new issue should be made for this problem.

I looked at the image, but I do not see any white textures? Could you specify this further?

> ![image](https://user-images.githubusercontent.com/84128082/125312149-f052f700-e32b-11eb-9230-3d269cc8fd73.png)
> The second problem would be, as seen above, the newly added characters all have white hair. This is an error on my end that I can't seem to find a solution for and I think before closing this issue, this problem needs to be solved.

It might be due to the fact that the texture of hair models you are trying to use is missing? Assure that the Human Hair Component has a texture available in it, like with Mikasa as an example:
![image](https://user-images.githubusercontent.com/22615133/126880996-130b0183-caed-4d2a-83bb-7abfa1916dae.png)

**Comment by sxlksxskul** [comment]
![image](https://user-images.githubusercontent.com/84128082/126987959-047ccd4e-1575-4cb6-8e9b-abd7099e6a38.png)

> I looked at the image, but I do not see any white textures? Could you specify this further?

Do you see the area around his eyes and nose, how the skin is a very light colour. Then look towards his hair at the side (at least the area where he would have hair since he is bald) and around his ears. The skin there is a completely different shade from the front of his face (the area area around his eyes and nose). It's a very sudden change in shades that looks a bit off-putting. Not sure if this was made intentionally or not but I think this should be changed so that the entire head has the same shade of colour (personal opinion).

> It might be due to the fact that the texture of hair models you are trying to use is missing? Assure that the Human Hair Component has a texture available in it, like with Mikasa as an example:

Nope not the problem, I put the textures for everybody's hair, I compared the existing Human Hair Components with the ones I made, from what I can see, they are identical completely, the models and textures themselves. I also checked if the materials for the hair textures were different, but they are also the same. The properties for everything also look identical from what I saw before, unless there is like a hidden property or I somehow used the wrong textures (which I also doubt is the case but I'll double check again) I have no idea what could be the problem, maybe the textures themselves? No clue.

**Comment by Lithrun** [comment]
> Do you see the area around his eyes and nose, how the skin is a very light colour. Then look towards his hair at the side (at least the area where he would have hair since he is bald) and around his ears. The skin there is a completely different shade from the front of his face (the area area around his eyes and nose). It's a very sudden change in shades that looks a bit off-putting. Not sure if this was made intentionally or not but I think this should be changed so that the entire head has the same shade of colour (personal opinion).

It looks like that because of the texture itself, so the texture itself would need to be updated.

> Nope not the problem, I put the textures for everybody's hair, I compared the existing Human Hair Components with the ones I made, from what I can see, they are identical completely, the models and textures themselves. I also checked if the materials for the hair textures were different, but they are also the same. The properties for everything also look identical from what I saw before, unless there is like a hidden property or I somehow used the wrong textures (which I also doubt is the case but I'll double check again) I have no idea what could be the problem, maybe the textures themselves? No clue.

Hm alright, I will investigate this and see if I can find the issue. Stay tuned~

**Comment by Lithrun** [comment]
![image](https://user-images.githubusercontent.com/22615133/127025169-b1ca6948-5f62-49ec-aef7-6916e21bd47f.png)
Apparently there is no hair color set for those characters? If it's 0, 0, 0, 0, then it will just use the textures default color.

There is a small bug with the editor script, as you have to increase the size of the inspector window, otherwise you will not be able to see certain fields, which might explain why the color appeared to be missing to you?
