### ISSUE TITLE
Reverse hook

### ISSUE THREAD

**Issue by KoroSensei0320** [AoTTG-2/AoTTG-2#81]
**How will this enhancement improve the game?**
It will help players avoid certain threats by being able to shoot themselves backwards.

**Describe the solution you'd like**
Set a key that can shoot an ODMG hook backwards.

**Additional context**
Add any other context or screenshots about the feature request here. https://youtu.be/CeLvx_1FBdk?t=37
Seen here at 40 seconds.
------
https://youtu.be/C1843Q-adWI?t=15
Seen at 15-19 seconds, very clear view.

**Comment by JupiterJaeden** [comment]
This doesn't really make sense given how odm gear works in AOTTG (and by extension AOTTG2). You aim a cursor to shoot a hook at where that cursor is aimed, having a reverse hook serves no real purpose except maybe to look cool. How would the aiming even work? Would you have a separate cursor to aim your reverse hook? This just really doesn't make sense.

**Comment by KoroSensei0320** [comment]
I agree that some of these issues that are added by voting aren’t incredibly useful. 
Aiming should be backward/down, to pull you backwards if you need to quickly get out of a situation (though most plays will use the normal controls.) and aiming isn’t really required.
- accidentally closed this issue, then reopened.

**Comment by JupiterJaeden** [comment]
So... you just wouldn't aim the hook? How would you even know it was going to hit something? After all, you can't see behind you (and if you could, then why not just turn around and fire your hook normally). This feature is worse than useless, I think it would be actively confusing.

**Comment by KoroSensei0320** [comment]
Well, I didn’t propose the feature, I’m just the one adding it to GitHub.

**Comment by JupiterJaeden** [comment]
Ah, fair enough lol. I seriously think we should consider dropping/closing this as it makes absolutely no sense. But if the community wants it...

**Comment by SlowDeepExhalation** [comment]
A reverse hook could use something like the current both hooks mechanic.  The game already autoaims both hooks to grappleable surfaces close to your reticle, and isn't *entirely* terrible at picking a useful target.  A reverse hook could use the same mechanic, just flipped to aim at something behind you.  You could even put a dot under the reticle that turns green or red depending on whether the autoaim system has targeted something close enough.  That would make it fairly predictable and *somewhat* reliable, though I suspect it'd still be little more than a crutch for newbies.

**Comment by JupiterJaeden** [comment]
The difference is that the current both hooks mechanic still depends on you aiming your cursor. And "autoaim" is a bit of a stretch, it's always the same distance apart so the one doing the actual "aiming" is still you. And if you make the "reverse hook" aiming the same (i.e. it depends on you aiming your cursor), then there is no reason why you couldn't just turn around and aim.

**Comment by SlowDeepExhalation** [comment]
I pulled open RCMod just to check, and yeah, you're right, there's no autoaim on both hooks.  I was mistaken, because I don't have it bound and so have only noticed its very strange reticle behavior.

What it *actually* does is fire the two hooks 45 degrees angles off of your reticle, but the two extra reticles adjust to show the impact location, which makes sense.  This can make it massively change how far away they are from the main reticle, often making them jump across the screen to closer obstacles, and is part of why I thought it was actually aiming the hooks.

...Also, strangely, the *rotation* that both hooks are fired at changes *based on the character's facing*.  If your character is facing north, but you fire directly west, the hooks will be vertical.  If you fire them south, the left hook (Q) will go towards the *right* reticle mark.  This is very strange, considering how much it changes the action's behavior, despite character facing being extremely chaotic during flight.  It's the other reason why I thought both hooks had autoaim--I'd noticed that it seemed to try and switch to vertical alignment to target pillars in racing sometimes, and assumed it just did a terrible job of figuring out *when* to adjust this.

This all being said, I still believe a limited autoaim system could be implemented for backwards hook.  Actually looking around and targeting an object behind you would probably be too expensive, but you could have it fire a limited shotgun spread of raycasts behind the camera, and select the first one that intersects with an object.  That would be fairly decent at grabbing something behind you if it's large and relatively close, though it might miss small/thin objects, and would require *some* degree of thought on the player's part.

For the record, I don't actually support backwards hooks.  The game already has 10+ buttons that are actively used during *basic manuevering*, it's hard to add more without sacrificing old controls.  I just want to help come up with an implementation that is theoretically useful, since the community voted for it to be implemented.

**Comment by Lithrun** [comment]
Issue will not be implemented.
