### ISSUE TITLE
GAMM!

### ISSUE THREAD

**Issue by KoroSensei0320** [AoTTG-2/AoTTG-2#82]
**Describe the solution you'd like**
 Implement another mode for using gas to move on air.
Controversial feature, although 83% agreed to add it to the game. You may want to make it optional in a lobby or test thoroughly to make sure it is not overpowered and will change the game too much. 

You need to press a key / hold a key (to be determined) to activate the GAMM ( Gas Aerial Maneuver Mode ). While this mode is active, you will consume a lot more gas, receive a "burst" stream of gas, but you will be able to manipulate your movement depending on where your camera is looking. Useful when you want to rapidly change your movement speed to avoid collisions (or give it an extra speed boost)

Extra details on burst:
It is similar to what we know in Aottg "gas bursts" but could be sustained for longer duration and is manually operated instead of pushing you instantly for 5 meters or so. It doesn't build up but a fixed(debatable, but should at least have a minimum of 50mps at the start after turning on and applies to gas after turning on) speed is maintained when just using gas ( to push you on a direction ). There are times they use gas to change view/directions.

Source material references:
Jean used a hook downwards, in Aottg game, but while gas should only accelerate you downwards since you hooked downwards he managed to move at a higher speed descent with GAMM evading the hand and rotates to the back of Annie while using GAMM again to push himself upwards, no hooks used.
https://youtu.be/mAKrZFfp8DY?t=48 (52-55s)

Levi used gas only to rotate to the back of the beast titan and move downward to the legs using GAMM , the hook is for him to stop himself smashing to the ground.
https://youtu.be/gQJyCtELWaU?t=40

**Comment by Lithrun** [comment]
Due to the potential impact of this feature depending on its implementation, please re-poll on Discord before we start working on this one.

**Comment by ExtraLemon** [comment]
I'm concerned for how this will affect racing maps - won't having the ability to accelerate upwards without hooks basically make all long jumps trivial?

**Comment by Lithrun** [comment]
> 
> 
> I'm concerned for how this will affect racing maps - won't having the ability to accelerate upwards without hooks basically make all long jumps trivial?

If we decide to implement this feature (will re-poll as previously mentioned), it can be seen as an aimed boost. Which means that players will also be able to manipulate their vertical velocity instead of just a horizontal one which the current boost has.

For racing this would make existing long jumps a lot easier, since previously players could only change their vertical velocity via hooks. If the community wants to have this mechanic, then racing maps should take this in consideration for new maps. There will be new racing maps created by the community that can make use of this feature and perhaps require a long jump where horizontal and vertical boosting is required.

As an ultimatum, if we presume that there's a 50/50 on the poll, we could also make the feature a setting that can be enabled / disabled by the MC.

**Comment by ExtraLemon** [comment]
Ok, so all racing maps pre-AOTTG 2 will essentially be made worthless - you could just GAMM past all the obstacles, especially holes and long jumps. This seems like far too much control given far too easily, and I really hope the repoll goes the other way.

**Comment by ExtraLemon** [comment]
Also, anime source material really shouldn't be used for 3DMG - anime 3DMG is inconsistent in its mechanics and only serves to look cool:
Survey Corps + Levi casually hooking onto thin air: http://www.youtube.com/watch?v=YHsKkZH4lfg&t=1m38s
Levi demonstrating his flight abilities without using any gas at all: https://www.youtube.com/watch?v=5JaO2usnBN8&t=3m56s 
Historia hooking onto thin air: http://www.youtube.com/watch?v=hb7wIeeYhyo&t=3m15s
You may claim that they're hooking onto trees/buildings out of frame, but if you actually watch a few seconds later, you see that the buildings are either A: absurdly far away or B: nowhere near the actual height they were going. There's many more examples of this, but trying to copy anime 3dmg is hopeless.

**Comment by SlowDeepExhalation** [comment]
As a person who pretty much only plays AoTTG for lava racing, I agree that GAMM is a negative feature and would trivialize many racing maps.  However, speaking as the devil's advocate, I could see it potentially adding *some* value.  Since it doesn't interfere with any old mechanics, it could possibly allow new kinds of obstacles to be created, and since it is extremely inefficient, maps could be built around rationing its use.  It could arguably also help beginners get into racing, as an easy mode would make the many repeated deaths of lava racing a bit easier to bear.  IF it could be prevented from interfering with traditional gameplay, adding it is unlikely to be particularly *harmful*.  Which I admit very reluctantly.

That being said, I feel a simple "ban GAMM" option inpause menu options wouldn't be enough.  If I were calling the shots, I'd probably ban GAMM entirely from normal racing mode, and add a "racing practice" mode which can have it enabled, along with different visuals and victory text.  That would ensure that screenshots of race times are "legit", and would probably placate most racers--they could just ignore the new mode and mechanic, and newbies to racing would intuitively understand that GAMM is essentially training wheels which makes races easier in trade for worse times.

**Comment by JupiterJaeden** [comment]
There is a very simple solution to this: Keep it as a very low-priority feature, then if later down the line a dev comes along who is willing to work on it, just have it be a server-wide option that is disabled by default and can be enabled by the MC.

**Comment by Lithrun** [comment]
Issue will not be implemented into AoTTG2.
