### ISSUE TITLE
[3D Model Request] Light source

### ISSUE THREAD

**Issue by CoronaryLilim** [AoTTG-2/AoTTG-2#88]
**Information**
A small, hand-held flash-light used to light up the surroundings. 

**Why is this 3D Model needed?**
It can be used as a light source for players on foot in night maps and expeditions after dark.

**References**
<img width="1440" alt="Screen Shot 2020-04-18 at 12 34 55 AM" src="https://user-images.githubusercontent.com/61645271/79570549-bd608a00-810d-11ea-9513-eaa1f030f2b9.png">
This serves the exact purpose for what we are looking for, is the most accurate to the AOT universe, and is most practical.

**Comment by KoroSensei0320** [comment]
We've decided to model after the "torches" used in season 3 (seen in episode 13) instead
<img width="1440" alt="Screen Shot 2020-04-18 at 12 34 55 AM" src="https://user-images.githubusercontent.com/61645271/79570249-33b0bc80-810d-11ea-81ef-5630ccc8cff1.png">
 since they serve the same purpose as what we are trying to achieve.

**Comment by KoroSensei0320** [comment]
The flashlight has been modelled, and now requires cleaning & texturing.
